apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: caffeine-exchange
  name: caffeine-exchange
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caffeine-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: caffeine-exchange
    spec:
      containers:
      - image: scorsaro/micro-demo-caffeine-exchange-service:0.0.42-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-caffeine-exchange-service
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: caffeine-exchange
  name: caffeine-exchange
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: caffeine-exchange
  sessionAffinity: None
  type: LoadBalancer